# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

authors:
  jono:
    name: Jonathan Yeong
    display_name: jono
    gravatar: 7693460f070c2e00c78e56806d4fdfc0
    email: jonathanyeong@gmail.com
    web: http://jonathanyeong.com
    twitter: jonoyeong
    github: jonathanyeong
  wendy:
    name: Wendy Beth 
    display_name:
    gravatar:
    email:
    web: http://wendybeth.ghost.io
    twitter: wendybeth010
    github: WendyBeth
  jimmy:
    name: Jimmy Lo
    display_name:
    gravatar:
    email:
    web: http://jimmylocoding.com/
    twitter: jimmylocoding 
    github: jimmylorunning
